module.exports = {
  week: [
    [
      {
        id: 01,
        achievementScore: 980,
        nickname: "Lion91",
        rank: 1,
        profileImage: "",
      },
      {
        id: 02,
        achievementScore: 895,
        nickname: "HypeBoy",
        rank: 2,
        profileImage: "",
      },
      {
        id: 03,
        achievementScore: 760,
        nickname: "IronMan760",
        rank: 3,
        profileImage: "",
      },
      {
        id: 04,
        achievementScore: 710,
        nickname: "OMG",
        rank: 4,
        profileImage: "",
      },
      {
        id: 05,
        achievementScore: 705,
        nickname: "thomsongazelle72",
        rank: 5,
        profileImage: "",
      },
    ],
    [
      {
        id: 11,
        achievementScore: 680,
        nickname: "BTS",
        rank: 6,
        profileImage: "",
      },
      {
        id: 12,
        achievementScore: 670,
        nickname: "BlaCkPiNk",
        rank: 7,
        profileImage: "",
      },
      {
        id: 13,
        achievementScore: 550,
        nickname: "IronMan55",
        rank: 8,
        profileImage: "",
      },
    ],
    [
      {
        id: 21,
        achievementScore: 520,
        nickname: "thomsongazelle52",
        rank: 9,
        profileImage: "",
      },
      {
        id: 22,
        achievementScore: 490,
        nickname: "Rose1",
        rank: 10,
        profileImage: "",
      },
      {
        id: 23,
        achievementScore: 380,
        nickname: "IronMan38",
        rank: 11,
        profileImage: "",
      },
    ],
    [
      {
        id: 31,
        achievementScore: 520,
        nickname: "thomsongazelle52",
        rank: 12,
        profileImage: "",
      },
      {
        id: 32,
        achievementScore: 490,
        nickname: "Jisoo",
        rank: 13,
        profileImage: "",
      },
      {
        id: 33,
        achievementScore: 380,
        nickname: "IronMan38",
        rank: 14,
        profileImage: "",
      },
    ],
  ],
  month: [
    [
      {
        id: 1,
        achievementScore: 3600,
        nickname: "KingsMan",
        rank: 1,
        profileImage: "",
      },
      {
        id: 2,
        achievementScore: 3510,
        nickname: "BabyMonster",
        rank: 2,
        profileImage: "",
      },
      {
        id: 3,
        achievementScore: 3320,
        nickname: "IronMan3",
        rank: 3,
        profileImage: "",
      },
      {
        id: 4,
        achievementScore: 3250,
        nickname: "SecretAgent",
        rank: 4,
        profileImage: "",
      },
      {
        id: 5,
        achievementScore: 3230,
        nickname: "Jennie",
        rank: 5,
        profileImage: "",
      },
    ],
    [
      {
        id: 6,
        achievementScore: 3210,
        nickname: "Hulk",
        rank: 6,
        profileImage: "",
      },
      {
        id: 7,
        achievementScore: 3201,
        nickname: "UFCfighter",
        rank: 7,
        profileImage: "",
      },
      {
        id: 8,
        achievementScore: 3199,
        nickname: "SuperMan",
        rank: 8,
        profileImage: "",
      },
    ],
    [
      {
        id: 9,
        achievementScore: 3190,
        nickname: "BatMan",
        rank: 9,
        profileImage: "",
      },
      {
        id: 10,
        achievementScore: 3180,
        nickname: "SpiderMan2",
        rank: 10,
        profileImage: "",
      },
      {
        id: 11,
        achievementScore: 3150,
        nickname: "Zeus",
        rank: 11,
        profileImage: "",
      },
    ],
    [
      {
        id: 12,
        achievementScore: 3130,
        nickname: "Lisa",
        rank: 12,
        profileImage: "",
      },
      {
        id: 13,
        achievementScore: 3120,
        nickname: "InYourArea",
        rank: 13,
        profileImage: "",
      },
      {
        id: 14,
        achievementScore: 3105,
        nickname: "Rose",
        rank: 14,
        profileImage: "",
      },
    ],
  ],
};
